name: Deploy on Docker Hub

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
    
      -   name: Build and push stable Docker image
          uses: docker/build-push-action@v1.1.0
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: blkkkbvsik/plex-notifier
            dockerfile: Dockerfile
            # tag with the git commit SHA
            tag_with_sha: true
            tags: latest
            # push the image only if the event that kicked off the workflow was a push of a git tah
            push: ${{ startsWith(github.ref, 'refs/tags/') }}
